Update contents from 'java' to 'mvn'.

diff --git a/mvn-jni-wrapper/mvn b/mvn-jni-wrapper/mvn
--- a/mvn-jni-wrapper/mvn
+++ b/mvn-jni-wrapper/mvn
@@ -1,24 +1,25 @@
 #!/usr/bin/env sh
 #
 # Calling this script is equal to calling
-#	LD_LIBRARY_PATH="/usr/lib/jni" java
+#	export LD_LIBRARY_PATH="/usr/lib/jni" mvn
 #
 # This script adds the LD_LIBRARY_PATH option transparently, so that
-# it is available from all call sites that call `java` from the PATH.
+# it is available from all call sites that call `mvn` from the PATH.
 # The effect is that "/usr/lib/jni" is prepended to the dynamic library
-# search path. Note that it can still be overridden with the
+# search path. Note that it can still be overridden in java with the
 #	-Djava.library.path
 # option.
 
 # Get path to my install location
 fullpathself=$(readlink -f "$0")
 
-# Find actual `java` executable from $PATH
-JAVA=$(nextexec "${fullpathself}")
+# Find actual `mvn` executable from $PATH
+MVN=$(nextexec "${fullpathself}")
 
-if [ -z "${JAVA}" ] ; then
-	>&2 echo "$(readlink -f "$0") Error: No underlying java found from PATH."
+if [ -z "${MVN}" ] ; then
+	>&2 echo "$(readlink -f "$0") Error: No underlying mvn found from PATH."
 	exit 1
 fi
 
-exec env LD_LIBRARY_PATH="/usr/lib/jni" "${JAVA}" "$@"
+export LD_LIBRARY_PATH="/usr/lib/jni"
+exec "${MVN}" "$@"
