Add curly braces according to Google Shell Style Guide.
Guide is available at
https://google.github.io/styleguide/shell.xml?showone=Variable_expansion#Variable_expansion

Recommendation is to quote everything except built-ins.

diff --git a/java-jni-wrapper/java b/java-jni-wrapper/java
--- a/java-jni-wrapper/java
+++ b/java-jni-wrapper/java
@@ -14,11 +14,11 @@
 fullpathself=$(readlink -f "$0")
 
 # Find actual `java` executable from $PATH
-JAVA=$(nextexec "$fullpathself")
+JAVA=$(nextexec "${fullpathself}")
 
-if [ -z "$JAVA" ] ; then
-	>&2 echo "$(readlink -f "${0}") Error: No underlying java found from PATH."
+if [ -z "${JAVA}" ] ; then
+	>&2 echo "$(readlink -f "$0") Error: No underlying java found from PATH."
 	exit 1
 fi
 
-exec env LD_LIBRARY_PATH="/usr/lib/jni" "$JAVA" "$@"
+exec env LD_LIBRARY_PATH="/usr/lib/jni" "${JAVA}" "$@"
